name: CleanUpPullRequestPreviews

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  CleanUpPullRequestPreviews:
    if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client (pull request previews)
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.FRANKLIN_PRIV_PREVIEW }}
      - run: julia --project=.ci/ -e 'using Pkg; Pkg.develop(Pkg.PackageSpec(url = "https://github.com/bcbi/CleanUpPullRequestPreviews.jl.git"))'
      - run: julia --project=.ci/ -e 'using Pkg; Pkg.instantiate()'
      - name: CleanUpPullRequestPreviews.remove_old_previews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=.ci/ -e 'using CleanUpPullRequestPreviews; CleanUpPullRequestPreviews.remove_old_previews(; my_regex = r"^\.\/previews\/PR(\d*)", repo_main = "JuliaHealth/juliahealth.github.io", repo_previews = "git@github.com:JuliaHealth/juliahealth.github.io-previews.git", repo_previews_branch = "gh-pages")'
